=== Acensti/Voidcrew-LRP/_maps/ship_config_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": "string",
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": ["GENERAL", "PIRATES", "BRITISH_NAVY", "MERCANTILE", "REVOLUTIONARY", "SPACE", "NATURAL", "NATURAL_AGGRESSIVE", "BEASTS", "MYTHOLOGICAL", "HISTORICAL", "WEAPONS", "PILLS", "ENGINEERING"]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps\/([a-zA-Z0-9_/.]*)dmm$"
		},
		"map_id": {
			"title": "Map ID (DEPRECATED)",
			"type": "string",
			"description": "The ID of the ship class. Deprecated, code uses map_path instead."
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^\/datum\/outfit\/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"cost": {
			"title": "Class Cost",
			"type": "integer",
			"description": "The cost of the ship class, in credits.",
			"maximum": 116115990
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		},
		"disable_passwords": {
			"title": "Disable Passwords",
			"type": "boolean",
			"description": "Determines if passwords can be used on this ship",
			"default": false
		},
		"antag_datum": {
			"title": "Antag Datum",
			"type": "string",
			"description": "Allows you to grant all joiners an antag datum"
		}
	},

	"required": [
		"map_name",
		"map_path"
	]
}

=== Acensti/Voidcrew-LRP/_maps/configs/SYN-C_cyanide.json
{
    "map_name": "Cyanide-class Recon Vessel",
    "prefix": "SYN-C",
    "map_short_name": "Cyanide-class",
    "map_path": "_maps/shuttles/shiptest/voidcrew/cyanide.dmm",
    "map_id": "cyanide",
    "job_slots": {
        "Syndicate Recon Officer": {
            "outfit": "/datum/outfit/syndicate_empty/sbc/assault/captain",
            "officer": true,
            "slots": 1
        },
        "Syndicate Marine":{
            "outfit": "/datum/outfit/syndicate_empty/sbc/assault",
            "slots": 1
        }

    },
    "cost": 375,
	"disable_passwords": true
}

=== Acensti/Voidcrew-LRP/_maps/configs/NEU_afflictor.json
{
	"map_name": "Afflictor-Class Phase Frigate",
	"prefix": "NEU",
	"map_short_name": "Afflictor-Class",
	"map_path": "_maps/shuttles/shiptest/voidcrew/afflictor.dmm",
	"map_id": "afflictor",
	"job_slots": {
		"Captain": 1,
		"Geneticist": 1,
		"Station Engineer": 1,
		"Shaft Miner": 4
	},
	"cost": 450
}

=== Acensti/Voidcrew-LRP/_maps/configs/NT-C_starfire.json
{
	"map_name": "Starfire-class Atmospherics gasser",
	"map_short_name": "Starfire-class",
	"prefix": "NT-C",
	"map_path": "_maps/shuttles/shiptest/voidcrew/Atmosia.dmm",
	"map_id": "Atmosia",
	"job_slots": {
		"Captain": 1,
		"Atmospheric Technician": 3,
		"Security Officer": 3
    
	},
	"cost": 700
}

=== Acensti/Voidcrew-LRP/_maps/configs/NEU_catass.JSON
{
	"map_name": "Cat-class Boring Ass Ship",
	"prefix": "NEU",
	"namelists": ["GENERAL", "SPACE"],
	"map_short_name": "Cat-Class",
	"map_path": "_maps/shuttles/shiptest/voidcrew/catass.dmm",
	"map_id": "catass",
	"roundstart": true,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain",
			"officer": true,
			"slots": 1
		},
		"Research Director": {
			"outfit": "/datum/outfit/job/research_director",
			"slots": 1
			},
		"Chief Medical Officer": {
			"outfit": "/datum/outfit/job/chief_medical_officer",
			"slots": 1
			},
		"Chief Engineer": {
			"outfit": "/datum/outfit/job/chief_engineer",
			"slots": 1
		},
		"Miner": {
			"outfit": "/datum/outfit/job/shaft_miner",
			"slots": 4
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 5
		}
	},
	"cost": 750
}

=== Acensti/Voidcrew-LRP/_maps/configs/KOS_express_cultist.JSON
{
	"map_name": "KOS Express-Class Eldritch Hijacked Freighter",
	"map_short_name": "Cultist-class",
	"map_path": "_maps/shuttles/shiptest/voidcrew/express_cultist.dmm",
	"antag_datum": "cult",
	"map_id": "express_cultist",
	"job_slots": {
		"Cultist Leader": {
			"outfit": "/datum/outfit/job/captain/western",
			"officer": true,
			"slots": 1
		},
		"Converted Foreman": {
			"outfit": "/datum/outfit/job/quartermaster/western",
			"slots": 1
		},
		"Converted Engineer": {
			"outfit": "/datum/outfit/job/engineer/hazard",
			"slots": 1
		},
		"Converted Miner": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 2
		},
		"Cultist": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 3
		}
	}
}

=== Acensti/Voidcrew-LRP/_maps/configs/NEU_mechaton-VOID.json
{
	"map_name": "Mechaton-class Robotics Production Facility",
	"map_short_name": "Mechaton-class",
	"prefix": "NEU",
	"map_path": "_maps/shuttles/shiptest/voidcrew/mechaton.dmm",
	"map_id": "mechaton",
	"job_slots": {
		"Facility Director": {
			"outfit": "/datum/outfit/job/rd",
			"officer": true,
			"slots": 1
		},
		"Roboticist": {
			"outfit": "/datum/outfit/job/roboticist",
			"slots": 2
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/engineer",
			"slots": 2
		},
		"Mech Pilot": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 2
		}
	},
	"cost": 350
}
